// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    Number.prototype.monthToString = function() {
      var months;
      months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
      return months[this.valueOf()] || "Not a valid month";
    };
    return Date.prototype.cleanFormat = function() {
      return this.getMonth().monthToString() + " " + this.getFullYear();
    };
  });

}).call(this);
