// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    /* Router*/

    window.Workspace = Backbone.Router.extend({
      routes: {
        "saved": "saved",
        "settings": "settings",
        "map/:index/(:subview)": "goto"
      },
      goto: function() {
        return cc(arguments);
      },
      saved: function(rt) {
        cc("showing all maps");
        return launchModal("All Saved Maps", {
          destroyHash: true
        });
      },
      settings: function() {
        cc("showing settings");
        return launchModal("Your Settings", {
          destroyHash: true
        });
      }
    });
    window.app = new window.Workspace();
    return Backbone.history.start();
  });

}).call(this);
