// Generated by CoffeeScript 1.6.3
(function() {
  window.GoogleMap = function(model) {
    this.mapOptions = {
      center: new google.maps.LatLng(35, -62),
      zoom: 3,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    this.map = new google.maps.Map(document.getElementById("map-canvas"), this.mapOptions);
    this.infowindow = new google.maps.InfoWindow();
    this.model = model || null;
    this.markers = model.get("markers") || [];
    return this;
  };

  window.GoogleMap.prototype.plotStory = function(story) {
    var articleModel, display, marker, that;
    articleModel = story;
    marker = new views.MapMarker({
      model: story
    });
    marker = marker.render().marker;
    display = marker.el;
    this.markers.push(marker);
    marker.setMap(this.map);
    articleModel.set("marker", marker);
    that = this;
    google.maps.event.addListener(marker, "click", function() {
      cc(that.model);
      that.infowindow.setContent(display);
      return that.infowindow.open(that.map, this);
    });
    return this;
  };

}).call(this);
