// Generated by CoffeeScript 1.6.3
(function() {
  window.launchModal = function(content) {
    var modal;
    modal = $("<div />").addClass("modal");
    if ($.isArray(content)) {
      _.each(content, function(item) {
        return modal.append(item);
      });
    } else {
      modal.html(content);
    }
    modal.prepend("<i class='close-modal icon-untitled-7'></i>");
    modal.find(".close-modal").on("click", function() {
      $(document.body).removeClass("active-modal");
      return modal.remove();
    });
    $(document.body).addClass("active-modal").append(modal);
    return modal;
  };

  window.GoogleMap = function(model) {
    this.mapOptions = {
      center: new google.maps.LatLng(0, 0),
      zoom: 2,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    this.map = new google.maps.Map(document.getElementById("map-canvas"), this.mapOptions);
    this.infowindow = new google.maps.InfoWindow();
    this.model = model || null;
    this.markers = model.get("markers") || [];
    return this;
  };

  window.GoogleMap.prototype.plotStory = function(story) {
    var display_string, marker, pt, that, xOff, yOff;
    xOff = Math.random() * 0.1;
    yOff = Math.random() * 0.1;
    pt = new google.maps.LatLng(parseInt(story.latitude) + xOff, parseInt(story.longitude) + yOff);
    display_string = "<h3><a target='_blank' href='" + story.unescapedUrl + "'>" + story.title + "</a></h3>" + "<p>" + story.content + "</p>";
    marker = new google.maps.Marker({
      position: pt,
      title: story.title
    });
    this.markers.push(marker);
    marker.setMap(this.map);
    that = this;
    return google.maps.event.addListener(marker, "click", function() {
      cc(that.model);
      that.infowindow.setContent(display_string);
      return that.infowindow.open(that.map, this);
    });
  };

}).call(this);
