// Generated by CoffeeScript 1.6.3
(function() {
  window.GoogleMap = function(model) {
    this.mapOptions = {
      center: new google.maps.LatLng(35, -62),
      zoom: 3,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    this.map = new google.maps.Map(document.getElementById("map-canvas"), this.mapOptions);
    this.infowindow = new google.maps.InfoWindow();
    this.model = model || null;
    this.markers = model.get("markers") || [];
    return this;
  };

  window.GoogleMap.prototype.plotStory = function(story) {
    var articleModel, display_string, marker, pt, that, xOff, yOff;
    articleModel = story;
    story = story.toJSON();
    xOff = Math.random() * 0.1;
    yOff = Math.random() * 0.1;
    pt = new google.maps.LatLng(parseInt(story.latitude) + xOff, parseInt(story.longitude) + yOff);
    display_string = "<h3><a target='_blank' href='" + story.unescapedUrl + "'>" + story.title + "</a></h3>" + "<p>" + story.content + "</p>";
    marker = new google.maps.Marker({
      position: pt,
      animation: google.maps.Animation.DROP,
      title: story.title
    });
    this.markers.push(marker);
    marker.setMap(this.map);
    articleModel.set("marker", marker);
    that = this;
    google.maps.event.addListener(marker, "click", function() {
      cc(that.model);
      that.infowindow.setContent(display_string);
      return that.infowindow.open(that.map, this);
    });
    return this;
  };

}).call(this);
